[test]
startup_wait = 10000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[features]
seeds = true
skip-lint = false
[programs.localnet]
example = "QkQCdKYB5XywZWAGSAsSf8A4K1n4J1N6GzpmBaZYzxZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
